# Generated by Django 5.2.3 on 2025-07-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('continente', models.CharField(max_length=30)),
                ('capital', models.CharField(max_length=50)),
                ('idioma_oficial', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
