# Generated by Django 5.2.3 on 2025-07-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='idioma_oficial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
