# Generated by Django 5.2.3 on 2025-07-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primer_app', '0003_remove_pais_idioma_oficial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organismos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('siglas', models.CharField(max_length=15)),
                ('descripcion', models.TextField()),
                ('paises_miembros', models.ManyToManyField(to='mi_primer_app.pais')),
            ],
        ),
    ]
