# Generated by Django 5.2.3 on 2025-07-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primer_app', '0004_organismos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organismos',
            name='paises_miembros',
        ),
        migrations.RemoveField(
            model_name='organismos',
            name='siglas',
        ),
        migrations.AddField(
            model_name='organismos',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organismos',
            name='nombre',
            field=models.CharField(max_length=300),
        ),
    ]
