# Generated by Django 5.2.3 on 2025-07-08 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primer_app', '0005_remove_organismos_paises_miembros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organismos',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='organismos',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organismos',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
