# Generated by Django 5.2.3 on 2025-07-08 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primer_app', '0006_organismos_activo_alter_organismos_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acuerdos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(default=datetime.date(2000, 1, 1))),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
